name: todo
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  win32: ^5.0.8
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_storage: ^2.0.3
  get: ^4.6.6
  flutter_local_notifications: ^14.1.1
  #  flutter_native_timezone: ^2.0.0
  intl: ^0.18.1
  google_fonts: ^5.1.0
  date_picker_timeline: ^1.2.3
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.3.0
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^2.0.7
  rxdart: ^0.27.2
  timezone: ^0.9.2
  flutter_timezone: ^1.0.7
  googleapis: ^13.1.0
  googleapis_auth: ^1.4.1
  google_sign_in: ^6.3.0
  http: ^1.1.0
  flutter_dotenv: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2

flutter_icons:
  android: true
  ios: true
  image_path: "images/appicon.jpeg"

flutter:
  uses-material-design: true

  assets:
    - images/person.jpeg
    - images/task.svg
    - .env